// The 15 pages carried over from WordPress (export of 28 September 2026).
// Generated by code/import_wordpress.py - never paraphrase in wp-pages.json.
import data from "./wp-pages.json";

export type WpPage = {
  path: string;
  oldPath: string | null;
  title: string;
  description: string;
  name: string;
  date: string;
  needs: string[];
  hasMain: boolean;
  html: string;
};

export const wpPages = data as WpPage[];
export const wpPage = (path: string) => wpPages.find((p) => p.path === path);
